version: '3.8'

services:
  nginx:
    image: nginxproxy/nginx-proxy:1.4.0
    container_name: nginx-proxy
    restart: unless-stopped
    networks:
      - nginx_proxy_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
  acme:
    image: cilenco/lego-cron-wrapper:v4.14.2
    container_name: nginx-certs
    restart: unless-stopped
    networks:
      - nginx_proxy_network
      - nginx_host_network
    command: >
      --accept-tos --email=${EMAIL} --dns ionos
      --domains=*.${DOMAIN} --domains=${DOMAIN}
    # --server=https://acme-staging-v02.api.letsencrypt.org/directory
    environment:
      - RUN_ARGUMENTS: --run-hook=/app/deploy
      - RENEW_ARGUMENTS: --renew-hook=/app/deploy
      - IONOS_API_KEY_FILE: /app/credentials
      - IONOS_PROPAGATION_TIMEOUT: 120
      - IONOS_POLLING_INTERVAL: 20
    volumes:
      - certs:/app/certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./credentials:/app/credentials
      - ./deploy.sh:/app/deploy

networks:
  nginx_proxy_network:
    name: nginx_proxy_network
  nginx_host_network:
    name: nginx_host_network
    driver: macvlan
    driver_opts:
      parent: eth0

volumes:
  certs:
    external: true
