version: '3.8'
    
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=c-dielitz.de
      - VIRTUAL_PORT=9091
    volumes:
      - ./config:/config
