# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: light #light/dark
jwt_secret: ${JWT_SECRET}

default_redirection_url: https://google.com/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug

totp:
  issuer: ${DOMAIN}
  period: 30
  skew: 1

authentication_backend:
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    ## bypass rule
    - domain: "${DOMAIN}"
      policy: bypass
    - domain: "dns.${DOMAIN}" # Adguard Home
      policy: one_factor
    - domain: "dancing.${DOMAIN}" # Outline Wiki
      policy: one_factor
    - domain: "video.${DOMAIN}" # Jellyfin server
      policy: one_factor
    - domain: "home.${DOMAIN}" # Home Assistant
      policy: one_factor
    
session:
  name: authelia_session
  secret: ${SESSION_SECRET}
  domain: ${DOMAIN}
  expiration: 1h
  inactivity: 5m


regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: ${ENCRYPTION_KEY}
  local:
    path: /config/db.sqlite3

  
notifier:
  disable_startup_check: true #true/false
  smtp:
    username: youremail@gmail.com #your email address
    password: Y0uRp@55W0rD! #your email password
    host: smtp.gmail.com #email smtp server
    port: 587 #email smtp port
    sender: youremail@gmail.com
    identifier: localhost
    subject: "[Authelia] {title}" #email subject
    startup_check_address: youremail@gmail.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
