version: '3.8'

services:
  authelia:
    image: authelia/authelia:latest
    network_mode: nginx_default
    container_name: authelia
    restart: unless-stopped
    environment:
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE: /secrets/OIDC_PRIVATE_KEY
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /secrets/OIDC_HMAC_SECRET
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
      VIRTUAL_HOST: auth.${DOMAIN}
      VIRTUAL_PORT: 9091
    volumes:
      - ./config:/config
      - ./secrets:/secrets
