version: "3.8"

services:
  homeassistant:    
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: home-server
    network_mode: host
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      VIRTUAL_PORT: 8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      - ./config:/config      
    privileged: true
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: home-matter
    network_mode: host
    environment:
      NETWORK_ACCESS: internal
    security_opt:
      - apparmor=unconfined
    volumes:
      - /run/dbus:/run/dbus:ro
      - ./matter:/data    
