services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    networks:
      - nginx_ip4_network
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "cloud.${DOMAIN}"
      VIRTUAL_PORT: 80

networks:
  nginx_ip4_network:
    external: true
