version: "3.8"

services:
  nextcloud:
    image: nextcloud
    network_mode: nginx_default
    container_name: nextcloud
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "cloud.${DOMAIN}"
      VIRTUAL_PORT: 80
