version: "3.8"

services:
  otbr:
    image: siliconlabsinc/openthread-border-router:gsdk-4.4.0
    command: --radio-url spinel+hdlc+uart:///dev/ttyUSB0?uart-baudrate=460800 --backbone-interface eth0
    container_name: home-thread
    restart: unless-stopped
    privileged: true
    networks:
      - home_network
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    ports:
      - 8080:80
      - 8081:8081
    dns:
      - 127.0.0.1
    volumes:
      - /dev/ttyUSB0:/dev/ttyUSB0

networks:
  home_network:
    external: true
