version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: outline-redis
    network_mode: nginx_default
    restart: unless-stopped
    environment:
      NETWORK_ACCESS: internal
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: outline-db
    network_mode: nginx_default
    restart: unless-stopped
    env_file: env.outline
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      NETWORK_ACCESS: internal
      POSTGRES_DB: outline
  outline:
    image: outlinewiki/outline:latest
    container_name: outline-server
    network_mode: nginx_default
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "dancing.${DOMAIN}"
      VIRTUAL_PORT: 3000
    env_file: env.outline
    volumes:
      - ./data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
