version: "3.8"

services:
  adguard:
    image: adguard/adguardhome
    network_mode: nginx_default
    container_name: adguard
    ports:
      - "853:853/tcp"
      - "853:853/udp"
      - "3000:3000"
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      VIRTUAL_PORT: 80
    volumes:
      - certs:/opt/adguardhome/certs:ro
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart:
      unless-stopped

volumes:
  certs:
    external: true
