services:
  spliit-app:
    image: spliit2:latest
    container_name: spliit-app
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    env_file:
      - container.env
    environment:
      VIRTUAL_HOST: "pay.${DOMAIN}"
      VIRTUAL_PORT: 3000
    depends_on:
      spliit-db:
        condition: service_healthy

  spliit-db:
    image: postgres:latest
    container_name: spliit-db
    restart: unless-stopped
    networks:
      - nginx_ip4_network
    ports:
      - 5432:5432
    env_file:
      - container.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
